# Generated by Django 5.2.3 on 2025-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValdivianoApp', '0002_boleta_detalleboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(default='activa', max_length=20),
        ),
    ]
