# Generated by Django 5.2.3 on 2025-07-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValdivianoApp', '0003_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('gramos', 'Gramos'), ('unidad', 'Unidad')], default='unidad', max_length=10),
        ),
    ]
