# Generated by Django 5.2.3 on 2025-07-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValdivianoApp', '0004_producto_tipo_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.JSONField()),
                ('boleta_original_id', models.IntegerField()),
                ('archivada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
