# Generated by Django 5.2.3 on 2025-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValdivianoApp', '0005_boletahistorica'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleboleta',
            name='tipo_venta',
            field=models.CharField(choices=[('gramos', 'Gramos'), ('unidad', 'Unidad')], default='unidad', max_length=10),
        ),
    ]
